version: '3.3'

services:
    management1:
        image: mysql/mysql-cluster
        networks:
            cluster:
                ipv4_address: 192.168.0.2
        command: ndb_mgmd

    ndb1:
        image: mysql/mysql-cluster
        networks:
            cluster:
                ipv4_address: 192.168.0.3
        command: ndbd
        depends_on:
            - management1

    ndb2:
        image: mysql/mysql-cluster
        networks:
            cluster:
                ipv4_address: 192.168.0.4
        command: ndbd
        depends_on:
            - management1
            - ndb1

    mysql1:
        image: mysql/mysql-cluster
        environment:
            - "MYSQL_RANDOM_ROOT_PASSWORD=true"
        networks:
            cluster:
                ipv4_address: 192.168.0.10
        volumes:
            - db_data:/var/lib/mysql
        command: mysqld
        depends_on:
            - management1
            - ndb1
            - ndb2

volumes:
    db_data: {}

networks:
    cluster:
        ipam:
            config:
                - subnet: 192.168.0.0/16
